import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import Ridge
from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, root_mean_squared_error
import joblib

def train_and_export_models(csv_path):
    print(f"Loading empirical dataset from: {csv_path}")
    df = pd.read_csv(csv_path)

    # ---------------------------------------------------------
    # 1. Data Preprocessing & Feature Engineering
    # ---------------------------------------------------------
    # We only use features available AT THE EDGE before a routing decision is made.
    
    # Features for Edge Model (Focuses on local compute constraints)
    edge_features = ['image_size_bytes', 'edge_cpu_utilization', 'edge_memory_utilization']
    X_edge = df[edge_features]
    y_edge_latency = df['edge_total_latency_ms']

    # Features for Cloud Model (Focuses on network constraints and payload size)
    cloud_features = ['image_size_bytes', 'network_rtt_ms', 'estimated_uplink_bandwidth_kbps']
    X_cloud = df[cloud_features]
    y_cloud_latency = df['cloud_total_latency_ms']
    y_cloud_cost = df['estimated_cloud_cost_usd']

    # Chronological Split (To simulate real-world streaming data and prevent temporal leakage)
    # We don't shuffle. We take the first 80% for training and the last 20% for testing.
    split_idx = int(len(df) * 0.8)
    
    X_edge_train, X_edge_test = X_edge.iloc[:split_idx], X_edge.iloc[split_idx:]
    y_edge_lat_train, y_edge_lat_test = y_edge_latency.iloc[:split_idx], y_edge_latency.iloc[split_idx:]
    
    X_cloud_train, X_cloud_test = X_cloud.iloc[:split_idx], X_cloud.iloc[split_idx:]
    y_cloud_lat_train, y_cloud_lat_test = y_cloud_latency.iloc[:split_idx], y_cloud_latency.iloc[split_idx:]
    y_cloud_cost_train, y_cloud_cost_test = y_cloud_cost.iloc[:split_idx], y_cloud_cost.iloc[split_idx:]

    print("\n--- Training Edge Latency Model (Ridge Regression) ---")
    # Ridge Regression maps linear scaling of CPU-bound image processing
    edge_lat_model = Ridge(alpha=1.0)
    edge_lat_model.fit(X_edge_train, y_edge_lat_train)
    
    edge_preds = edge_lat_model.predict(X_edge_test)
    print(f"Edge Latency MAE: {mean_absolute_error(y_edge_lat_test, edge_preds):.2f} ms")
    print(f"Edge Latency RMSE: {root_mean_squared_error(y_edge_lat_test, edge_preds):.2f} ms")

    print("\n--- Training Cloud Latency Model (GBRT) ---")
    # Gradient Boosted Regression Trees capture non-linear network jitter and AWS cold start probabilities
    cloud_lat_model = GradientBoostingRegressor(n_estimators=100, learning_rate=0.1, max_depth=3, random_state=42)
    cloud_lat_model.fit(X_cloud_train, y_cloud_lat_train)
    
    cloud_preds = cloud_lat_model.predict(X_cloud_test)
    print(f"Cloud Latency MAE: {mean_absolute_error(y_cloud_lat_test, cloud_preds):.2f} ms")
    print(f"Cloud Latency RMSE: {root_mean_squared_error(y_cloud_lat_test, cloud_preds):.2f} ms")

    print("\n--- Training Cloud Cost Model (GBRT) ---")
    cloud_cost_model = GradientBoostingRegressor(n_estimators=50, learning_rate=0.1, max_depth=3, random_state=42)
    cloud_cost_model.fit(X_cloud_train, y_cloud_cost_train)
    
    cost_preds = cloud_cost_model.predict(X_cloud_test)
    print(f"Cloud Cost MAE: ${mean_absolute_error(y_cloud_cost_test, cost_preds):.6f}")

    # ---------------------------------------------------------
    # 2. Serialization (Exporting Models for Phase 3)
    # ---------------------------------------------------------
    print("\n--- Serializing Models ---")
    joblib.dump(edge_lat_model, '../backend/models/edge_latency_model.pkl')
    joblib.dump(cloud_lat_model, '../backend/models/cloud_latency_model.pkl')
    joblib.dump(cloud_cost_model, '../backend/models/cloud_cost_model.pkl')
    print("Successfully exported: edge_latency_model.pkl, cloud_latency_model.pkl, cloud_cost_model.pkl")

if __name__ == "__main__":
    # Point this to the latest dataset generated by benchmark.py
    # Ensure you are using the large 1,000 image dataset for best results!
    LATEST_CSV = "../benchmark_results_20260426_222931.csv"
    train_and_export_models(LATEST_CSV)
